# One-off generator for remediation/tracker.json (kept for provenance; edit tracker.json directly afterwards).
import json
P = {'W0':0,'S1':1,'W1':1,'W2':1,'W3':2,'W4':2,'W5':2,'W6':2,'W8a':2,'W10a':2,'W7':3,'W8b':3,'W9':4,'W10':4,'W11':4,'W12':4}
F = lambda f: {'file': f}
T = lambda f, t: {'file': f, 'title': t}
rows = [
# id, sev, ws, title, tests
('SEC-1','P0','W1','Operation batches accepted before handshake (unauthenticated writes)',[F('SEC-1.test.ts')]),
('SEC-2','P0','W1','Upload authorization trusts client previousData/data instead of the stored row',[F('SEC-2.test.ts')]),
('SEC-3','P1','W1','op.nodeId not bound to session; forged sequence silently drops a victim\'s offline writes',[F('SEC-3.test.ts')]),
('SEC-4','P2','W1','Handshake response leaks the full server version vector',[F('SEC-4.test.ts')]),
('SEC-5','P0','W1','Yjs, awareness and blob relays bypass auth and scope',[F('SEC-5.test.ts')]),
('SEC-6','P1','W1','Route-context scope check ignores stored row; limit applied before scope',[F('SEC-6.test.ts')]),
('SEC-7','P3','W12','SQL injection via orderBy direction / limit / offset (local store)',[F('SEC-7.test.ts')]),
('SEC-8','P2','W1','Auth token sent in the WebSocket URL',[F('SEC-8.test.ts')]),
('SEC-9a','P2','W1','request.ip trusts spoofed X-Forwarded-For',[T('SEC-9.test.ts','(a)')]),
('SEC-9b','P3','W12','Unescaped quotes in DDL defaults',[T('SEC-9.test.ts','(b)')]),
('NEW-SEC-1','P3','W1','Route-context scope matcher ignores $in',[F('NEW-SEC-1.test.ts')]),
('NEW-SEC-2','P0','W1','previousData.id forgery bypasses id-scoped uplink checks',[T('LMS-8.test.ts','forged previousData.id must not authorize an update'),T('LMS-8.test.ts','forged previousData.id must not authorize a delete'),T('LMS-8.test.ts','insert whose recordId is in an id-scoped uplink')]),
('AUTH-1','P0','W2','Sync scope is client-controlled; handshake can widen access',[F('AUTH-1.test.ts'),T('LMS-11.test.ts','must NOT be widened'),T('LMS-11.test.ts','must NOT become writable')]),
('AUTH-2','P1','W2','Revoked device keeps working via refresh and HTTP routes',[F('AUTH-2.test.ts')]),
('AUTH-3','P1','W2','OAuth state not bound to initiator or purpose (link CSRF takeover)',[F('AUTH-3.test.ts')]),
('AUTH-4','P1','W2','Invitations claimable by anyone; cross-org revoke',[F('AUTH-4.test.ts')]),
('AUTH-5','P1','W2','Client-chosen deviceId not bound to user (lockout attack)',[F('AUTH-5.test.ts')]),
('AUTH-6','P2','W2','Concurrent refreshes with one token both succeed',[F('AUTH-6.test.ts')]),
('AUTH-7','P1','W2','Reset token disclosed without callback; reset does not revoke sessions',[F('AUTH-7.test.ts')]),
('AUTH-8','P2','W2','Sign-out does not stop the access token on HTTP routes',[F('AUTH-8.test.ts')]),
('AUTH-9','P2','W2','Account enumeration by timing; weak sign-in rate limit',[F('AUTH-9.test.ts')]),
('AUTH-10','P1','W2','MFA not enforced at issuance; TOTP brute force and replay',[F('AUTH-10.test.ts')]),
('AUTH-11','P1','W2','Live sync sessions never re-checked after revocation or expiry',[F('AUTH-11.test.ts')]),
('AUTH-12','P2','W2','In-memory revocation store in quickstart; no persistent store ships',[F('AUTH-12.test.ts')]),
('AUTH-13','P0','W2','Offline users are signed out and their refresh token destroyed',[F('AUTH-13.test.ts'),T('LMS-1.test.ts','transient refresh failures'),T('LMS-1.test.ts','bounded in time'),F('LMS-2.test.ts')]),
('AUTH-14','P3','W2','Passkey UV, external JWT exp/aud/iss, webhook replay/SSRF, AdminApi authz',[F('AUTH-14.test.ts')]),
('NEW-AUTH-1','P1','W2','One retried refresh permanently bans the device from sync',[F('NEW-AUTH-1.test.ts')]),
('NEW-AUTH-2','P1','W2','Two tabs refreshing at once sign out every tab',[T('LMS-1.test.ts','two tabs sharing token storage')]),
('NEW-AUTH-3','P1','W2','Lost rotation response triggers reuse-detection sign-out',[T('LMS-1.test.ts','lost refresh response')]),
('NEW-AUTH-4','P2','W2','restoreSession treats a 401 from /auth/me as offline',[]),
('SYNC-1','P0','W3','Own edits leaving a query subset are never uploaded',[F('SYNC-1.test.ts'),T('LMS-9.test.ts','must not be silently kept local-only')]),
('SYNC-2','P1','W4','Inbound ops filtered by uplink scope (read-only data dropped)',[F('SYNC-2.test.ts'),T('LMS-9.test.ts','downlink {c1,c2}, uplink {c1}'),T('LMS-9.test.ts','[fails today] read-only learner')]),
('SYNC-3','P1','W4','Non-success apply results advance the watermark (ops lost)',[F('SYNC-3.test.ts')]),
('SYNC-4','P1','W3','Acks not matched to batches; handshake-delta ops dropped before ack',[F('SYNC-4.test.ts')]),
('SYNC-5','P2','W5','Engine goes offline without closing the transport; sockets leak',[F('SYNC-5.test.ts')]),
('SYNC-6','P3','W3','OutboundQueue seen-set grows forever',[F('SYNC-6.test.ts')]),
('SYNC-7','P2','W4','One far-future op blocks the delivery stream',[F('SYNC-7.test.ts')]),
('SYNC-8','P2','W5','Reconnect backoff never grows',[F('SYNC-8.test.ts')]),
('SYNC-9','P3','W12','Protobuf negotiation lossy and unsafe if enabled',[F('SYNC-9.test.ts')]),
('SYNC-10','P3','W5','Timers and async sends outlive stop/close',[F('SYNC-10.test.ts')]),
('SYNC-11','P1','W4','Accepted-scope change wedges sync after first reconnect',[F('SYNC-11.test.ts')]),
('NEW-SYNC-1','P1','W4','Duplicate final batch never completes initial sync',[F('NEW-SYNC-1.test.ts')]),
('NEW-SYNC-2','P3','W5','Reconnect loop can miss a disconnect racing start()',[F('NEW-SYNC-2.test.ts')]),
('NEW-SYNC-3','P1','W4','Inbound insert dropped under id-scoped downlink',[T('LMS-8.test.ts','[fails today] inbound, non-directional'),T('LMS-8.test.ts','[fails today] inbound, directional')]),
('NEW-SYNC-4','P1','W4','Fresh client drops an update batched with its insert; watermark advances',[T('LMS-9.test.ts','[fails today] insert + partial update'),T('LMS-9.test.ts','[fails today] while the session stays up')]),
('ENC-1','P1','W9','Random salt per process: encryption cannot work across devices',[F('ENC-1.test.ts')]),
('ENC-2','P2','W4','Decrypt failure treated as a connection failure (infinite loop)',[F('ENC-2.test.ts')]),
('ENC-3','P2','W9','No AAD; plaintext accepted when encryption is on',[F('ENC-3.test.ts')]),
('NEW-ENC-1','P1','W9','Schema-aware server rejects every encrypted op',[F('NEW-ENC-1.test.ts')]),
('SRV-1','P1','W7','Server materialization differs from client merge',[F('SRV-1.test.ts')]),
('SRV-2','P1','W4','Record moving into scope arrives without its insert',[F('SRV-2.test.ts')]),
('SRV-3','P2','W4','Delivery stream re-sends unacked backlog on every write',[F('SRV-3.test.ts')]),
('SRV-4','P2','W10a','Postgres per-instance vector cache; dedup race; INTEGER overflow',[F('SRV-4.test.ts')]),
('SRV-5','P2','W4','Delivery stream buffers the whole backlog in memory',[F('SRV-5.test.ts')]),
('SRV-6','P1','W5','No heartbeat/timeouts/limits; HTTP sessions never expire; unbounded bodies',[F('SRV-6.test.ts'),T('LMS-12.test.ts','must probe an idle WebSocket'),T('LMS-12.test.ts','must be reaped after inactivity')]),
('SRV-7','P2','W7','No compaction; each write replays full record history',[F('SRV-7.test.ts')]),
('NEW-SRV-1','P3','W10','Memory store rebuild scans the whole log per write',[]),
('NEW-SRV-2','P3','W10a','Concurrent duplicate on Postgres runs the cascade twice',[]),
('NEW-SRV-3','P1','W4','Orphan updates stay forever after a missed scope entry',[]),
('NEW-SRV-4','P2','W10','Postgres backfill reruns fully on every restart',[T('LMS-10.test.ts','benchmark:')]),
('NEW-SRV-5','P1','W10','Backfill overwrites live writes during rolling deploy',[T('LMS-10.test.ts','must not overwrite a concurrent live write')]),
('NEW-SRV-6','P1','W10','Tombstones lose scope fields; deleted records reappear for scoped clients',[T('LMS-10.test.ts','deleted record must keep its scope fields')]),
('NEW-SRV-7','P2','W4','Retract mode looks up records for ops that can never exit scope',[T('LMS-11.test.ts','retract policy issues a record lookup')]),
('NEW-SRV-8','P2','W12','Static server: no validators/compression, SPA fallback for missing assets, wrong MIME',[T('LMS-13.test.ts','correct behaviour')]),
('STORE-1','P0','W6','app.transaction reuses sequence numbers; later writes never uploaded',[F('STORE-1.test.ts')]),
('STORE-2','P0','W6','Cascade deletes inside transactions collide on sequence numbers',[F('STORE-2.test.ts')]),
('STORE-3','P1','W6','Transactional writes skip per-field version stamps',[F('STORE-3.test.ts')]),
('STORE-4','P0','W6','Secret fields stored and synced in plaintext via transactions',[F('STORE-4.test.ts')]),
('STORE-5','P0','W8b','Backup restore corrupts timestamps and copies device identity',[F('STORE-5.test.ts')]),
('STORE-6','P1','W8b','IndexedDB follower tab overwrites the leader\'s live DB',[F('STORE-6.test.ts')]),
('STORE-7','P1','W8b','IndexedDB flushNow re-entrancy loses writes',[F('STORE-7.test.ts')]),
('STORE-8','P2','W6','execute/query bypass the adapter mutex',[F('STORE-8.test.ts')]),
('STORE-9','P1','W6','Concurrent atomic increments lose updates locally',[F('STORE-9.test.ts')]),
('STORE-10','P2','W6','Multi-tab: duplicate apply not notified; per-tab vectors',[F('STORE-10.test.ts')]),
('STORE-11','P2','W12','Documented createdAt/updatedAt queries throw',[F('STORE-11.test.ts')]),
('STORE-12','P2','W12','Subscription diff re-notifies; errors swallowed',[F('STORE-12.test.ts')]),
('STORE-13','P1','W8b','Migrations not atomic; backfills never sync',[F('STORE-13.test.ts')]),
('STORE-14','P2','W7','Compaction breaks fold and dedup',[F('STORE-14.test.ts')]),
('STORE-15','P3','W6','Dedup race, index name collisions, quota mapping',[F('STORE-15.test.ts')]),
('STORE-16','P3','W12','Benchmark gates do not measure the browser path',[]),
('NEW-STORE-1','P2','W8b','Backfill transform receives raw SQLite rows',[F('NEW-STORE-1.test.ts')]),
('NEW-STORE-2','P1','W6','Transactions bypass state machine validation',[F('NEW-STORE-2.test.ts')]),
('NEW-STORE-3','P1','W6','Field-level .transitions() never enforced',[F('NEW-STORE-3.test.ts')]),
('NEW-STORE-4','P2','W12','persist() awaited in startup (can hang ready); result discarded',[F('LMS-4.test.ts')]),
('NEW-STORE-5','P0','W8a','Origin-wide SAH pool vs per-DB leader: second DB non-durable or disjoint',[{'browser':'LMS-5b'},{'browser':'LMS-5c'}]),
('NEW-STORE-6','P0','W8a','Promoted leader silently runs in memory',[{'browser':'LMS-5f'}]),
('NEW-STORE-7','P0','W8a','Pool capacity exhaustion bricks writes for every user',[{'browser':'LMS-6a'}]),
('NEW-STORE-8','P1','W8a','Failed open leaks worker and leader lock',[{'browser':'LMS-6c'}]),
('NEW-STORE-9','P2','W8a','Hung leader not detected; no failover',[F('LMS-7.test.ts'),{'browser':'LMS-7b'}]),
('NEW-STORE-10','P2','W8a','close() releases leader lock before the pool holder stops',[]),
('NEW-STORE-11','P3','W12','PRAGMA WAL is a no-op on sahpool; spec says WAL',[]),
('MERGE-1','P1','W7','Array merge loses one-sided removals',[F('MERGE-1.test.ts')]),
('MERGE-2','P0','W7','Pairwise merge diverges permanently for arrays and objects',[F('MERGE-2.test.ts')]),
('NEW-MERGE-1','P0','W7','Unchanged array in a concurrent update undoes a removal (2 devices)',[F('NEW-MERGE-1.test.ts')]),
('CORE-1','P2','W7','Op id hash omits fields; ids never verified on receive',[F('CORE-1.test.ts')]),
('DX-1','P1','W11','Insert/record types are vacuous (FieldBuilder phantom params)',[{'tsc':'kora/tests/repro/types/DX-1.ts'}]),
('DX-2','P2','W11','where/orderBy/include/transactions/useCollection untyped',[{'tsc':'kora/tests/repro/types/DX-2.ts'}]),
('DX-3','P2','W12','Docs contradict the code (first-run tutorial crashes)',[F('DX-3.test.ts')]),
('DX-4','P3','W12','findById before ready returns null silently',[F('DX-4.test.ts')]),
('DX-5','P3','W12','useMutation unstable identities and resubscribes',[F('DX-5.test.ts')]),
('DX-6','P2','W12','SSR broken (getServerSnapshot, eager native SQLite)',[F('DX-6.test.ts')]),
('DX-7','P2','W12','Vue useQuery not reactive to input changes',[F('DX-7.test.ts')]),
('DX-8','P3','W12','Deploy prompt offers stub platforms',[F('DX-8.test.ts')]),
('DX-9','P3','W12','Shadowed collection names give no runtime warning',[F('DX-9.test.ts')]),
('NEW-DX-1','P2','W12','useCollaborators has no getServerSnapshot',[]),
('NEW-DX-2','P3','W12','DynamicProtobufSerializer is dead code',[]),
('NEW-DX-3','P1','W12','Scaffolded apps cannot open offline (no service worker)',[{'browser':'NEW-DX-3'}]),
]
stopgaps = {'STORE-4':'S1','SYNC-1':'S1','STORE-1':'S1','MERGE-1':'S1','NEW-MERGE-1':'S1','NEW-STORE-6':'S1','NEW-STORE-7':'S1'}
out = []
for (i,s,w,t,tests) in rows:
    e = {'id':i,'title':t,'severity':s,'workstream':w,'phase':P[w],'status':'open','tests':tests}
    if i in stopgaps: e['stopgap'] = {'workstream':'S1','phase':1,'status':'open'}
    if not tests: e['acceptance'] = 'No dedicated repro yet: write one when the workstream starts (plan section 4, W0 acceptance checks).'
    e['pr'] = None; e['notes'] = ''
    out.append(e)
assert len(out) == 107 and len({o['id'] for o in out}) == 107
json.dump({'version':1,'source':'remediation/evidence/kora-fix-plan.md','statuses':['open','in_progress','mitigated','fixed','wontfix'],'problems':out}, open('remediation/tracker.json','w'), indent=1)
print(len(out))
