import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const GENERATED_HEADER = '# Generated by kora deploy — do not edit manually'

/**
 * Configuration for generating a production Dockerfile.
 */
export interface DockerfileOptions {
	nodeVersion?: string
	port?: number
	clientDirectory?: string | null
	serverBundleFile?: string
	/** Native modules that must be installed at runtime (externalized from bundle). */
	nativeDependencies?: Record<string, string>
}

/**
 * Generates a multi-stage Dockerfile for Kora deployments.
 *
 * The generated image expects artifacts produced under `.kora/deploy`:
 * - `dist/` for client assets
 * - `server-bundled.js` for server runtime entry
 * - `package.json` (if native dependencies are needed)
 */
export function generateDockerfile(options: DockerfileOptions = {}): string {
	const nodeVersion = options.nodeVersion ?? '20-alpine'
	const port = options.port ?? 3000
	const clientDirectory = options.clientDirectory === undefined ? 'dist' : options.clientDirectory
	const serverBundleFile = options.serverBundleFile ?? 'server-bundled.js'
	const hasNativeDeps =
		options.nativeDependencies && Object.keys(options.nativeDependencies).length > 0

	const lines: string[] = [
		GENERATED_HEADER,
		'',
		`FROM node:${nodeVersion} AS runtime`,
		'WORKDIR /app',
		'ENV NODE_ENV=production',
		`ENV PORT=${String(port)}`,
		'',
	]

	if (hasNativeDeps) {
		// Alpine needs build tools for native modules like better-sqlite3
		lines.push('# Install build tools for native modules')
		lines.push('RUN apk add --no-cache python3 make g++')
		lines.push('')
		lines.push('COPY package.json ./package.json')
		lines.push('RUN npm install --omit=dev')
		lines.push('')
	}

	if (clientDirectory !== null) {
		lines.push(`COPY ${clientDirectory} ./dist`)
	}
	lines.push(`COPY ${serverBundleFile} ./server-bundled.js`)
	lines.push('')
	lines.push(`EXPOSE ${String(port)}`)
	lines.push('CMD ["node", "./server-bundled.js"]')
	lines.push('')

	return lines.join('\n')
}

/**
 * Generates a minimal package.json for native dependencies in the deploy container.
 */
export function generateDeployPackageJson(nativeDependencies: Record<string, string>): string {
	const pkg = {
		name: 'kora-deploy',
		version: '1.0.0',
		private: true,
		type: 'module',
		dependencies: nativeDependencies,
	}
	return `${JSON.stringify(pkg, null, 2)}\n`
}

/**
 * Generates a `.dockerignore` tuned for Kora deploy output.
 */
export function generateDockerIgnore(): string {
	return [
		GENERATED_HEADER,
		'',
		'node_modules',
		'npm-debug.log*',
		'pnpm-debug.log*',
		'yarn-error.log*',
		'.env',
		'.env.*',
		'.git',
		'.gitignore',
		'coverage',
		'.turbo',
		'*.test.ts',
		'*.spec.ts',
		'',
	].join('\n')
}

/**
 * Writes the generated Dockerfile (and package.json if needed) to `.kora/deploy/`.
 */
export async function writeDockerfileArtifact(
	deployDirectory: string,
	options: DockerfileOptions = {},
): Promise<string> {
	await mkdir(deployDirectory, { recursive: true })
	const dockerfilePath = join(deployDirectory, 'Dockerfile')
	await writeFile(dockerfilePath, generateDockerfile(options), 'utf-8')

	if (options.nativeDependencies && Object.keys(options.nativeDependencies).length > 0) {
		const pkgJsonPath = join(deployDirectory, 'package.json')
		await writeFile(pkgJsonPath, generateDeployPackageJson(options.nativeDependencies), 'utf-8')
	}

	return dockerfilePath
}

/**
 * Writes the generated `.dockerignore` to `.kora/deploy/.dockerignore`.
 */
export async function writeDockerIgnoreArtifact(deployDirectory: string): Promise<string> {
	await mkdir(deployDirectory, { recursive: true })
	const dockerIgnorePath = join(deployDirectory, '.dockerignore')
	await writeFile(dockerIgnorePath, generateDockerIgnore(), 'utf-8')
	return dockerIgnorePath
}
