import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const GENERATED_HEADER = '# Generated by kora deploy — do not edit manually'

/**
 * Configuration for generating a production Dockerfile.
 */
export interface DockerfileOptions {
	nodeVersion?: string
	port?: number
	clientDirectory?: string
	serverBundleFile?: string
}

/**
 * Generates a multi-stage Dockerfile for Kora deployments.
 *
 * The generated image expects artifacts produced under `.kora/deploy`:
 * - `dist/` for client assets
 * - `server-bundled.js` for server runtime entry
 */
export function generateDockerfile(options: DockerfileOptions = {}): string {
	const nodeVersion = options.nodeVersion ?? '20-alpine'
	const port = options.port ?? 3000
	const clientDirectory = options.clientDirectory ?? 'dist'
	const serverBundleFile = options.serverBundleFile ?? 'server-bundled.js'

	return [
		GENERATED_HEADER,
		'',
		`FROM node:${nodeVersion} AS runtime`,
		'WORKDIR /app',
		'ENV NODE_ENV=production',
		`ENV PORT=${String(port)}`,
		'',
		`COPY ${clientDirectory} ./dist`,
		`COPY ${serverBundleFile} ./server-bundled.js`,
		'',
		'EXPOSE 3000',
		'CMD ["node", "./server-bundled.js"]',
		'',
	].join('\n')
}

/**
 * Generates a `.dockerignore` tuned for Kora deploy output.
 */
export function generateDockerIgnore(): string {
	return [
		GENERATED_HEADER,
		'',
		'node_modules',
		'npm-debug.log*',
		'pnpm-debug.log*',
		'yarn-error.log*',
		'.env',
		'.env.*',
		'.git',
		'.gitignore',
		'coverage',
		'.turbo',
		'*.test.ts',
		'*.spec.ts',
		'',
	].join('\n')
}

/**
 * Writes the generated Dockerfile to `.kora/deploy/Dockerfile`.
 */
export async function writeDockerfileArtifact(
	deployDirectory: string,
	options: DockerfileOptions = {},
): Promise<string> {
	await mkdir(deployDirectory, { recursive: true })
	const dockerfilePath = join(deployDirectory, 'Dockerfile')
	await writeFile(dockerfilePath, generateDockerfile(options), 'utf-8')
	return dockerfilePath
}

/**
 * Writes the generated `.dockerignore` to `.kora/deploy/.dockerignore`.
 */
export async function writeDockerIgnoreArtifact(deployDirectory: string): Promise<string> {
	await mkdir(deployDirectory, { recursive: true })
	const dockerIgnorePath = join(deployDirectory, '.dockerignore')
	await writeFile(dockerIgnorePath, generateDockerIgnore(), 'utf-8')
	return dockerIgnorePath
}
