import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, test } from 'vitest'
import {
	generateDockerIgnore,
	generateDockerfile,
	writeDockerIgnoreArtifact,
	writeDockerfileArtifact,
} from './dockerfile-generator'

describe('dockerfile-generator', () => {
	const createdDirs: string[] = []

	afterEach(async () => {
		for (const dir of createdDirs.splice(0)) {
			await import('node:fs/promises').then((fs) => fs.rm(dir, { recursive: true, force: true }))
		}
	})

	test('generates Dockerfile with default runtime settings', () => {
		const content = generateDockerfile()
		expect(content).toContain('# Generated by kora deploy — do not edit manually')
		expect(content).toContain('FROM node:20-alpine AS runtime')
		expect(content).toContain('COPY dist ./dist')
		expect(content).toContain('COPY server-bundled.js ./server-bundled.js')
		expect(content).toContain('CMD ["node", "./server-bundled.js"]')
	})

	test('generates Dockerfile with custom options', () => {
		const content = generateDockerfile({
			nodeVersion: '22-alpine',
			port: 8080,
			clientDirectory: 'client-dist',
			serverBundleFile: 'custom-server.js',
		})
		expect(content).toContain('FROM node:22-alpine AS runtime')
		expect(content).toContain('ENV PORT=8080')
		expect(content).toContain('COPY client-dist ./dist')
		expect(content).toContain('COPY custom-server.js ./server-bundled.js')
	})

	test('generates dockerignore with expected exclusions', () => {
		const content = generateDockerIgnore()
		expect(content).toContain('node_modules')
		expect(content).toContain('.env')
		expect(content).toContain('.git')
		expect(content).toContain('*.test.ts')
	})

	test('writes Dockerfile and dockerignore artifacts', async () => {
		const root = await mkdtemp(join(tmpdir(), 'kora-docker-artifacts-'))
		createdDirs.push(root)
		const deployDirectory = join(root, '.kora', 'deploy')

		const dockerfilePath = await writeDockerfileArtifact(deployDirectory)
		const dockerIgnorePath = await writeDockerIgnoreArtifact(deployDirectory)

		const dockerfile = await readFile(dockerfilePath, 'utf-8')
		const dockerIgnore = await readFile(dockerIgnorePath, 'utf-8')
		expect(dockerfile).toContain('Generated by kora deploy')
		expect(dockerIgnore).toContain('Generated by kora deploy')
	})
})
