import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, test } from 'vitest'
import { generateFlyToml, writeFlyTomlArtifact } from './fly-toml-generator'

describe('fly-toml-generator', () => {
	const tempDirs: string[] = []

	afterEach(async () => {
		for (const dir of tempDirs) {
			await import('node:fs/promises').then(({ rm }) => rm(dir, { recursive: true, force: true }))
		}
		tempDirs.length = 0
	})

	test('generateFlyToml includes generated header and app metadata', () => {
		const source = generateFlyToml({
			appName: 'demo-kora-app',
			region: 'iad',
		})

		expect(source).toContain('# Generated by kora deploy — do not edit manually')
		expect(source).toContain('app = "demo-kora-app"')
		expect(source).toContain('primary_region = "iad"')
		expect(source).toContain('internal_port = 3000')
	})

	test('writeFlyTomlArtifact writes fly.toml into deploy directory', async () => {
		const tempDir = await mkdtemp(join(tmpdir(), 'kora-fly-toml-'))
		tempDirs.push(tempDir)

		const filePath = await writeFlyTomlArtifact(tempDir, {
			appName: 'demo-kora-app',
			region: 'lhr',
			internalPort: 4100,
		})
		const source = await readFile(filePath, 'utf-8')

		expect(filePath).toBe(join(tempDir, 'fly.toml'))
		expect(source).toContain('app = "demo-kora-app"')
		expect(source).toContain('primary_region = "lhr"')
		expect(source).toContain('internal_port = 4100')
	})
})
