import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const GENERATED_HEADER = '# Generated by kora deploy — do not edit manually'

/**
 * Configuration options used to render `fly.toml`.
 */
export interface FlyTomlOptions {
	appName: string
	region: string
	internalPort?: number
}

/**
 * Generates a minimal Fly.io configuration file for Kora sync apps.
 */
export function generateFlyToml(options: FlyTomlOptions): string {
	const internalPort = options.internalPort ?? 3000

	return [
		GENERATED_HEADER,
		'',
		`app = "${options.appName}"`,
		`primary_region = "${options.region}"`,
		'',
		'[build]',
		`  dockerfile = "Dockerfile"`,
		'',
		'[http_service]',
		`  internal_port = ${String(internalPort)}`,
		'  force_https = true',
		'  auto_stop_machines = "stop"',
		'  auto_start_machines = true',
		'  min_machines_running = 0',
		'',
		'  [[http_service.checks]]',
		'    grace_period = "10s"',
		'    interval = "30s"',
		'    method = "GET"',
		'    timeout = "5s"',
		'    path = "/health"',
		'',
	].join('\n')
}

/**
 * Writes `fly.toml` into `.kora/deploy`.
 */
export async function writeFlyTomlArtifact(
	deployDirectory: string,
	options: FlyTomlOptions,
): Promise<string> {
	await mkdir(deployDirectory, { recursive: true })
	const filePath = join(deployDirectory, 'fly.toml')
	await writeFile(filePath, generateFlyToml(options), 'utf-8')
	return filePath
}
