import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const GENERATED_HEADER = 'Generated by kora deploy - do not edit manually.'

/**
 * Configuration used to render `railway.json`.
 */
export interface RailwayJsonOptions {
	appName: string
	region: string
	startCommand?: string
	healthcheckPath?: string
}

interface RailwayJsonFile {
	$schema: string
	build: {
		builder: string
		dockerfilePath: string
	}
	deploy: {
		startCommand: string
		healthcheckPath: string
		restartPolicyType: 'on_failure'
		restartPolicyMaxRetries: number
	}
	metadata: {
		generatedBy: string
		appName: string
		region: string
	}
}

/**
 * Generates Railway deployment configuration in JSON format.
 */
export function generateRailwayJson(options: RailwayJsonOptions): string {
	const file: RailwayJsonFile = {
		$schema: 'https://railway.app/railway.schema.json',
		build: {
			builder: 'DOCKERFILE',
			dockerfilePath: 'Dockerfile',
		},
		deploy: {
			startCommand: options.startCommand ?? 'node ./server-bundled.js',
			healthcheckPath: options.healthcheckPath ?? '/health',
			restartPolicyType: 'on_failure',
			restartPolicyMaxRetries: 3,
		},
		metadata: {
			generatedBy: GENERATED_HEADER,
			appName: options.appName,
			region: options.region,
		},
	}

	return `${JSON.stringify(file, null, 2)}\n`
}

/**
 * Writes `railway.json` into `.kora/deploy`.
 */
export async function writeRailwayJsonArtifact(
	deployDirectory: string,
	options: RailwayJsonOptions,
): Promise<string> {
	await mkdir(deployDirectory, { recursive: true })
	const filePath = join(deployDirectory, 'railway.json')
	await writeFile(filePath, generateRailwayJson(options), 'utf-8')
	return filePath
}
