import type { SchemaDefinition } from '@korajs/core'

/**
 * Generates per-collection React hook stubs from a schema.
 *
 * @param schema - Validated schema definition
 * @returns Map of file basename to file contents
 */
export function generateCollectionHooks(schema: SchemaDefinition): Map<string, string> {
	const files = new Map<string, string>()

	for (const collectionName of Object.keys(schema.collections)) {
		const pascal = toPascalCase(collectionName)
		const hookName = `use${pascal}`

		const content = [
			'// Auto-generated by `kora generate hooks` — safe to edit',
			`// Schema v${String(schema.version)}`,
			'',
			"import { useCollection, useMutation, useQuery } from '@korajs/react'",
			`import type { ${pascal}InsertInput, ${pascal}Record, ${pascal}UpdateInput } from '../types'`,
			'',
			'/**',
			` * Collection hook for \`${collectionName}\`.`,
			' * Add useQuery(...) calls with your QueryBuilder factories.',
			' */',
			`export function ${hookName}() {`,
			`\tconst ${collectionName} = useCollection('${collectionName}')`,
			'',
			`\tconst insert = useMutation((data: ${pascal}InsertInput) => ${collectionName}.insert(data))`,
			`\tconst update = useMutation((id: string, data: ${pascal}UpdateInput) =>`,
			`\t\t${collectionName}.update(id, data),`,
			'\t)',
			`\tconst remove = useMutation((id: string) => ${collectionName}.delete(id))`,
			'',
			'\treturn {',
			`\t\t${collectionName},`,
			'\t\tinsert,',
			'\t\tupdate,',
			'\t\tremove,',
			'\t}',
			'}',
			'',
		].join('\n')

		files.set(`${collectionName}.ts`, content)
	}

	const indexLines = [
		'// Auto-generated by `kora generate hooks`',
		'',
		...Object.keys(schema.collections).map((name) => {
			const pascal = toPascalCase(name)
			return `export { use${pascal} } from './${name}'`
		}),
		'',
	]

	files.set('index.ts', indexLines.join('\n'))
	return files
}

function toPascalCase(value: string): string {
	return value
		.split(/[-_]/)
		.filter((part) => part.length > 0)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('')
}
