import type { FieldDescriptor, FieldKind, SchemaDefinition } from '@korajs/core'

/**
 * Generates TypeScript interfaces from a SchemaDefinition.
 * For each collection, produces three interfaces:
 * - {Name}Record: full record type (all fields + id)
 * - {Name}InsertInput: insert input (omit auto fields, optional for fields with defaults)
 * - {Name}UpdateInput: update input (all non-auto fields optional)
 *
 * @param schema - A validated SchemaDefinition from defineSchema()
 * @returns A complete TypeScript file as a string
 */
export function generateTypes(schema: SchemaDefinition): string {
	const lines: string[] = [
		'// Auto-generated by @korajs/cli — do not edit manually',
		`// Generated from schema version ${String(schema.version)}`,
		'',
	]

	const collectionNames = Object.keys(schema.collections)
	if (collectionNames.length === 0) {
		return lines.join('\n')
	}

	for (const [name, collection] of Object.entries(schema.collections)) {
		const pascal = toPascalCase(name)
		const fields = collection.fields

		// Record type: all fields + id
		lines.push(`export interface ${pascal}Record {`)
		lines.push('\treadonly id: string')
		for (const [fieldName, descriptor] of Object.entries(fields)) {
			const tsType = fieldKindToTypeScript(descriptor)
			const optional = !descriptor.required && !descriptor.auto ? '?' : ''
			lines.push(`\treadonly ${fieldName}${optional}: ${tsType}`)
		}
		lines.push('}')
		lines.push('')

		// Insert input: omit auto fields, optional for fields with defaults
		lines.push(`export interface ${pascal}InsertInput {`)
		for (const [fieldName, descriptor] of Object.entries(fields)) {
			if (descriptor.auto) continue
			const tsType = fieldKindToTypeScript(descriptor)
			const optional = !descriptor.required || descriptor.defaultValue !== undefined ? '?' : ''
			lines.push(`\t${fieldName}${optional}: ${tsType}`)
		}
		lines.push('}')
		lines.push('')

		// Update input: all non-auto fields optional
		lines.push(`export interface ${pascal}UpdateInput {`)
		for (const [fieldName, descriptor] of Object.entries(fields)) {
			if (descriptor.auto) continue
			const tsType = fieldKindToTypeScript(descriptor)
			lines.push(`\t${fieldName}?: ${tsType}`)
		}
		lines.push('}')
		lines.push('')
	}

	return lines.join('\n')
}

/** Maps a FieldDescriptor to its TypeScript type string */
function fieldKindToTypeScript(descriptor: FieldDescriptor): string {
	switch (descriptor.kind) {
		case 'string':
			return 'string'
		case 'number':
			return 'number'
		case 'boolean':
			return 'boolean'
		case 'timestamp':
			return 'number'
		case 'richtext':
			return 'string'
		case 'enum': {
			if (descriptor.enumValues && descriptor.enumValues.length > 0) {
				return descriptor.enumValues.map((v) => `'${v}'`).join(' | ')
			}
			return 'string'
		}
		case 'array': {
			const itemType = itemKindToTypeScript(descriptor.itemKind)
			return `Array<${itemType}>`
		}
		default:
			return 'unknown'
	}
}

/** Maps an item FieldKind to its TypeScript type string */
function itemKindToTypeScript(kind: FieldKind | null): string {
	switch (kind) {
		case 'string':
			return 'string'
		case 'number':
			return 'number'
		case 'boolean':
			return 'boolean'
		case 'timestamp':
			return 'number'
		case 'richtext':
			return 'string'
		case 'enum':
			return 'string'
		case 'array':
			return 'unknown[]'
		default:
			return 'unknown'
	}
}

/** Converts a snake_case or kebab-case name to PascalCase */
function toPascalCase(name: string): string {
	return name
		.split(/[_-]/)
		.map((part) => {
			if (part.length === 0) return ''
			const first = part[0]
			return first ? first.toUpperCase() + part.slice(1) : ''
		})
		.join('')
}
