import { defineSchema, t } from '@kora/core'
import { describe, expect, test } from 'vitest'
import { generateTypes } from './type-generator'

describe('generateTypes', () => {
	test('generates header comment with schema version', () => {
		const schema = defineSchema({
			version: 3,
			collections: {
				items: { fields: { name: t.string() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('Auto-generated by @kora/cli')
		expect(output).toContain('schema version 3')
	})

	test('maps string field to TypeScript string', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { title: t.string() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly title: string')
	})

	test('maps number field to TypeScript number', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { count: t.number() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly count: number')
	})

	test('maps boolean field to TypeScript boolean', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { active: t.boolean() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly active: boolean')
	})

	test('maps timestamp field to TypeScript number', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { created: t.timestamp() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly created: number')
	})

	test('maps richtext field to TypeScript string', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { body: t.richtext() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly body: string')
	})

	test('maps enum field to union of string literals', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: {
					fields: { priority: t.enum(['low', 'medium', 'high']) },
				},
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain("'low' | 'medium' | 'high'")
	})

	test('maps array field to Array<T>', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { tags: t.array(t.string()) } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('Array<string>')
	})

	test('marks optional fields with ? in Record type', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { note: t.string().optional() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly note?: string')
	})

	test('marks fields with defaults as optional in InsertInput', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { done: t.boolean().default(false) } },
			},
		})
		const output = generateTypes(schema)
		// In InsertInput, fields with defaults should be optional
		expect(output).toMatch(/export interface ItemsInsertInput \{[\s\S]*done\?: boolean/)
	})

	test('omits auto fields from InsertInput and UpdateInput', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: {
					fields: {
						title: t.string(),
						created_at: t.timestamp().auto(),
					},
				},
			},
		})
		const output = generateTypes(schema)

		// Record should have created_at
		expect(output).toMatch(/export interface ItemsRecord \{[\s\S]*created_at/)

		// InsertInput should NOT have created_at
		const insertSection = output.split('InsertInput')[1]?.split('export')[0] ?? ''
		expect(insertSection).not.toContain('created_at')

		// UpdateInput should NOT have created_at
		const updateSection = output.split('UpdateInput')[1]?.split('export')[0] ?? ''
		expect(updateSection).not.toContain('created_at')
	})

	test('generates all fields optional in UpdateInput', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: {
					fields: {
						title: t.string(),
						count: t.number(),
					},
				},
			},
		})
		const output = generateTypes(schema)
		expect(output).toMatch(/export interface ItemsUpdateInput \{[\s\S]*title\?: string/)
		expect(output).toMatch(/export interface ItemsUpdateInput \{[\s\S]*count\?: number/)
	})

	test('includes readonly id field in Record type', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				items: { fields: { title: t.string() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('readonly id: string')
	})

	test('converts snake_case collection name to PascalCase', () => {
		const schema = defineSchema({
			version: 1,
			collections: {
				user_profiles: { fields: { name: t.string() } },
			},
		})
		const output = generateTypes(schema)
		expect(output).toContain('export interface UserProfilesRecord')
		expect(output).toContain('export interface UserProfilesInsertInput')
		expect(output).toContain('export interface UserProfilesUpdateInput')
	})

	test('handles complex multi-collection schema', () => {
		const schema = defineSchema({
			version: 2,
			collections: {
				todos: {
					fields: {
						title: t.string(),
						completed: t.boolean().default(false),
						priority: t.enum(['low', 'medium', 'high']).default('medium'),
						tags: t.array(t.string()).default([]),
						notes: t.richtext(),
						due_date: t.timestamp().optional(),
						created_at: t.timestamp().auto(),
					},
					indexes: ['completed'],
				},
				projects: {
					fields: {
						name: t.string(),
						description: t.string().optional(),
					},
				},
			},
		})
		const output = generateTypes(schema)

		// Todos interfaces
		expect(output).toContain('export interface TodosRecord')
		expect(output).toContain('export interface TodosInsertInput')
		expect(output).toContain('export interface TodosUpdateInput')

		// Projects interfaces
		expect(output).toContain('export interface ProjectsRecord')
		expect(output).toContain('export interface ProjectsInsertInput')
		expect(output).toContain('export interface ProjectsUpdateInput')

		// Verify field types in TodosRecord
		expect(output).toContain('readonly title: string')
		expect(output).toContain('Array<string>')
		expect(output).toContain("'low' | 'medium' | 'high'")
	})

	test('returns only header for empty collections', () => {
		// We can't use defineSchema with empty collections (it throws),
		// so we test with a manually constructed SchemaDefinition
		const schema = {
			version: 1,
			collections: {} as Record<string, never>,
			relations: {},
		}
		const output = generateTypes(schema)
		expect(output).toContain('Auto-generated')
		expect(output).not.toContain('export interface')
	})
})
