/**
 * RT-10 repro (red team, 2026-10-01): referential side effects of a client delete are
 * generated by the server and applied without re-authorization, so deleting your own
 * parent cascades into (deletes or nulls) another tenant's children. The restrict
 * check also counts other tenants' children. Asserts the CORRECT behaviour.
 */
import { defineSchema, t } from '@korajs/core'
import type { SyncMessage } from '@korajs/sync'
import { describe, expect, test } from 'vitest'
import { TokenAuthProvider } from '../../src/auth/token-auth'
import { batch, createHarness, makeOp, tick } from './rt-fixture'

const collections = () => ({
	projects: { fields: { name: t.string(), userId: t.string() } },
	tasks: { fields: { title: t.string(), userId: t.string(), projectId: t.string().optional() } },
	comments: {
		fields: { body: t.string(), userId: t.string(), projectId: t.string().optional() },
	},
})

const schema = defineSchema({
	version: 1,
	collections: collections(),
	relations: {
		taskProject: {
			from: 'tasks',
			to: 'projects',
			type: 'many-to-one',
			field: 'projectId',
			onDelete: 'cascade',
		},
	},
})

const restrictSchema = defineSchema({
	version: 1,
	collections: collections(),
	relations: {
		commentProject: {
			from: 'comments',
			to: 'projects',
			type: 'many-to-one',
			field: 'projectId',
			onDelete: 'restrict',
		},
	},
})

function tenant(user: string) {
	return {
		userId: user,
		scopes: {
			projects: { userId: user },
			tasks: { userId: user },
			comments: { userId: user },
		},
	}
}

const auth = new TokenAuthProvider({
	validate: async (token) =>
		token.startsWith('alice') ? tenant('alice') : token.startsWith('bob') ? tenant('bob') : null,
})

function rejection(messages: SyncMessage[]): { code: string; message: string } | null {
	const m = messages.find((x) => x.type === 'operation-rejected')
	return m?.type === 'operation-rejected' ? { code: m.code, message: m.message } : null
}

describe('RT-10: referential side effects cross tenants', () => {
	test("deleting alice's project does not cascade into bob's task", async () => {
		const harness = await createHarness(schema, auth)
		const alice = await harness.login('alice-token', 'alice-node')
		const bob = await harness.login('bob-token', 'bob-node')
		const project = makeOp('alice-node', 1, {
			collection: 'projects',
			recordId: 'alice-project',
			data: { name: 'secret', userId: 'alice' },
		})
		alice.send(batch([project]))
		await tick()
		bob.send(
			batch([
				makeOp('bob-node', 1, {
					collection: 'tasks',
					recordId: 'bob-task',
					data: { title: 'mine', userId: 'bob', projectId: 'alice-project' },
				}),
			]),
		)
		await tick()
		expect(await harness.store.findRecord('tasks', 'bob-task')).not.toBeNull()
		alice.send(
			batch([
				makeOp('alice-node', 2, {
					type: 'delete',
					collection: 'projects',
					recordId: 'alice-project',
					data: null,
					causalDeps: [project.id],
				}),
			]),
		)
		await tick()
		const bobTask = await harness.store.findRecord('tasks', 'bob-task')
		expect(bobTask).not.toBeNull()
		expect(bobTask?._deleted ?? 0).toBe(0)
	})

	test('a restricted delete is refused with a generic RESTRICTED error (no ids, no counts)', async () => {
		const harness = await createHarness(restrictSchema, auth)
		const alice = await harness.login('alice-token', 'alice-node')
		const bob = await harness.login('bob-token', 'bob-node')
		const project = makeOp('alice-node', 1, {
			collection: 'projects',
			recordId: 'alice-project',
			data: { name: 'p', userId: 'alice' },
		})
		alice.send(batch([project]))
		await tick()
		bob.send(
			batch([
				makeOp('bob-node', 1, {
					collection: 'comments',
					recordId: 'bob-comment-xyz',
					data: { body: 'hi', userId: 'bob', projectId: 'alice-project' },
				}),
			]),
		)
		await tick()
		expect(await harness.store.findRecord('comments', 'bob-comment-xyz')).not.toBeNull()
		alice.send(
			batch([
				makeOp('alice-node', 2, {
					type: 'delete',
					collection: 'projects',
					recordId: 'alice-project',
					data: null,
					causalDeps: [project.id],
				}),
			]),
		)
		await tick()
		const refused = rejection(alice.messages)
		expect(refused?.code).toBe('RESTRICTED')
		expect(refused?.message).not.toContain('bob-comment-xyz')
		expect(refused?.message).not.toMatch(/\d+ (record|child|reference)/)
	})
})
