import { HybridLogicalClock } from '@korajs/core'
import type {
	MergeTrace,
	OnDeleteAction,
	Operation,
	RelationDefinition,
	SchemaDefinition,
} from '@korajs/core'

/**
 * Describes an incoming relation to a target collection.
 * Used by the delete-side referential integrity checker to know which
 * source collections reference the collection being deleted from.
 */
export interface MergeIncomingRelation {
	/** Name of the relation in the schema (e.g., 'todoBelongsToProject') */
	relationName: string
	/** The collection that holds the foreign key (source of the relation) */
	sourceCollection: string
	/** The foreign key field in the source collection */
	foreignKeyField: string
	/** What to do when the referenced record is deleted */
	onDelete: OnDeleteAction
}

/**
 * Pluggable context for querying the database during referential integrity checks.
 * The store layer provides the implementation; the merge package only depends on this interface.
 */
export interface ReferentialMergeContext {
	/** Query records in a collection matching a where clause */
	queryRecords(
		collection: string,
		where: Record<string, unknown>,
	): Promise<Record<string, unknown>[]>
	/** Check if a record exists in a collection */
	recordExists(collection: string, recordId: string): Promise<boolean>
}

/**
 * Result of a referential integrity check on a delete operation.
 */
export interface ReferentialCheckResult {
	/** Whether the delete operation is allowed to proceed */
	allowed: boolean
	/** Side-effect operations generated by cascade/set-null policies */
	sideEffectOps: SideEffectOp[]
	/** MergeTraces for every decision made (feeds DevTools) */
	traces: MergeTrace[]
}

/**
 * A side-effect operation generated during referential integrity enforcement.
 * These are not full Operations; they describe mutations the caller must apply.
 */
export interface SideEffectOp {
	/** The type of mutation to apply */
	type: 'delete' | 'update'
	/** The collection containing the affected record */
	collection: string
	/** The ID of the affected record */
	recordId: string
	/** For updates: the new field values. null for deletes. */
	data: Record<string, unknown> | null
	/** For updates: the previous field values. null for deletes. */
	previousData: Record<string, unknown> | null
	/** The onDelete policy that produced this side effect */
	policy: OnDeleteAction
	/** The relation that triggered this side effect */
	relationName: string
}

/**
 * Result of resolving a concurrent delete-vs-insert conflict.
 */
export interface DeleteVsInsertResolution {
	/** Whether to block the delete or allow it */
	action: 'block-delete' | 'allow-delete'
	/** Any side-effect operations (for cascade/set-null after allowing delete) */
	sideEffects: SideEffectOp[]
	/** Trace of the resolution decision, or null if no trace needed */
	trace: MergeTrace | null
}

/**
 * Builds a lookup map from target collection to all incoming relations.
 *
 * This pre-computes which collections reference a given collection via foreign keys,
 * so that delete operations can efficiently find all relations that need enforcement.
 *
 * @param schema - The full schema definition with relations
 * @returns Map from target collection name to array of incoming relations, sorted by relation name for determinism
 *
 * @example
 * ```typescript
 * const lookup = buildMergeRelationLookup(schema)
 * // lookup.get('projects') => [{ relationName: 'todoBelongsToProject', sourceCollection: 'todos', ... }]
 * ```
 */
export function buildMergeRelationLookup(
	schema: SchemaDefinition,
): Map<string, MergeIncomingRelation[]> {
	const lookup = new Map<string, MergeIncomingRelation[]>()

	// Collect all relation names and sort them for deterministic processing order
	const relationNames = Object.keys(schema.relations).sort()

	for (const relationName of relationNames) {
		const relation = schema.relations[relationName] as RelationDefinition | undefined
		if (relation === undefined) {
			continue
		}

		const targetCollection = relation.to
		const existing = lookup.get(targetCollection) ?? []
		existing.push({
			relationName,
			sourceCollection: relation.from,
			foreignKeyField: relation.field,
			onDelete: relation.onDelete,
		})
		lookup.set(targetCollection, existing)
	}

	// Sort each list by relation name for deterministic processing order.
	// buildMergeRelationLookup already inserts in sorted order because we
	// sort relationNames above, but this guarantees correctness regardless.
	for (const [, relations] of lookup) {
		relations.sort((a, b) =>
			a.relationName < b.relationName ? -1 : a.relationName > b.relationName ? 1 : 0,
		)
	}

	return lookup
}

/**
 * Checks referential integrity when a delete operation is being applied.
 *
 * For each relation that targets the deleted record's collection, queries
 * for referencing records and applies the relation's onDelete policy:
 * - `restrict`: Blocks the delete if any references exist
 * - `cascade`: Allows the delete and generates cascaded delete SideEffectOps
 * - `set-null`: Allows the delete and generates update SideEffectOps to null out FKs
 * - `no-action`: Allows the delete with no side effects (dangling references permitted)
 *
 * Processing is deterministic: relations are processed in sorted order by name,
 * and referencing records within each relation are processed in sorted order by ID.
 *
 * @param deleteOp - The delete operation being evaluated
 * @param schema - The full schema definition
 * @param ctx - Database lookup context
 * @param relationLookup - Pre-built relation lookup (optional; will be built if not provided)
 * @returns Whether the delete is allowed, any side-effect ops, and traces for DevTools
 */
export async function checkReferentialIntegrityOnDelete(
	deleteOp: Operation,
	schema: SchemaDefinition,
	ctx: ReferentialMergeContext,
	relationLookup?: Map<string, MergeIncomingRelation[]>,
): Promise<ReferentialCheckResult> {
	const lookup = relationLookup ?? buildMergeRelationLookup(schema)
	const incomingRelations = lookup.get(deleteOp.collection)

	// No relations target this collection — delete is always allowed
	if (incomingRelations === undefined || incomingRelations.length === 0) {
		return { allowed: true, sideEffectOps: [], traces: [] }
	}

	const allSideEffects: SideEffectOp[] = []
	const allTraces: MergeTrace[] = []

	// Process each incoming relation in deterministic order (already sorted by buildMergeRelationLookup)
	for (const relation of incomingRelations) {
		const startTime = Date.now()

		// Find all records in the source collection that reference the deleted record
		const referencingRecords = await ctx.queryRecords(relation.sourceCollection, {
			[relation.foreignKeyField]: deleteOp.recordId,
		})

		// Sort referencing records by ID for deterministic processing
		const sortedRecords = [...referencingRecords].sort((a, b) => {
			const idA = String(a.id ?? '')
			const idB = String(b.id ?? '')
			return idA < idB ? -1 : idA > idB ? 1 : 0
		})

		if (sortedRecords.length === 0) {
			// No references — this relation does not block the delete.
			// Create a trace recording that we checked and found nothing.
			const trace = createReferentialTrace(
				deleteOp,
				relation,
				`referential-${relation.onDelete}`,
				null,
				null,
				true,
				startTime,
			)
			allTraces.push(trace)
			continue
		}

		switch (relation.onDelete) {
			case 'restrict': {
				// Block the delete — references exist
				const trace = createReferentialTrace(
					deleteOp,
					relation,
					'referential-restrict',
					sortedRecords.map((r) => String(r.id ?? '')),
					null,
					false,
					startTime,
				)
				allTraces.push(trace)

				// Restrict means we immediately deny — no need to process further relations
				return {
					allowed: false,
					sideEffectOps: [],
					traces: allTraces,
				}
			}

			case 'cascade': {
				// Generate delete SideEffectOps for each referencing record
				for (const record of sortedRecords) {
					const recordId = String(record.id ?? '')
					allSideEffects.push({
						type: 'delete',
						collection: relation.sourceCollection,
						recordId,
						data: null,
						previousData: null,
						policy: 'cascade',
						relationName: relation.relationName,
					})
				}

				const trace = createReferentialTrace(
					deleteOp,
					relation,
					'referential-cascade',
					sortedRecords.map((r) => String(r.id ?? '')),
					sortedRecords.map((r) => ({ type: 'delete' as const, recordId: String(r.id ?? '') })),
					true,
					startTime,
				)
				allTraces.push(trace)
				break
			}

			case 'set-null': {
				// Generate update SideEffectOps setting the FK field to null
				for (const record of sortedRecords) {
					const recordId = String(record.id ?? '')
					const previousValue = record[relation.foreignKeyField]
					allSideEffects.push({
						type: 'update',
						collection: relation.sourceCollection,
						recordId,
						data: { [relation.foreignKeyField]: null },
						previousData: { [relation.foreignKeyField]: previousValue },
						policy: 'set-null',
						relationName: relation.relationName,
					})
				}

				const trace = createReferentialTrace(
					deleteOp,
					relation,
					'referential-set-null',
					sortedRecords.map((r) => String(r.id ?? '')),
					sortedRecords.map((r) => ({
						type: 'update' as const,
						recordId: String(r.id ?? ''),
						field: relation.foreignKeyField,
						newValue: null,
					})),
					true,
					startTime,
				)
				allTraces.push(trace)
				break
			}

			case 'no-action': {
				// Allow the delete, do nothing about dangling references
				const trace = createReferentialTrace(
					deleteOp,
					relation,
					'referential-no-action',
					sortedRecords.map((r) => String(r.id ?? '')),
					null,
					true,
					startTime,
				)
				allTraces.push(trace)
				break
			}
		}
	}

	return {
		allowed: true,
		sideEffectOps: allSideEffects,
		traces: allTraces,
	}
}

/**
 * Resolves a concurrent delete-vs-insert conflict on a referenced record.
 *
 * When one node deletes a record while another concurrently inserts a record
 * that references the deleted record, we need to decide what wins.
 *
 * Resolution strategy depends on the relation's onDelete policy:
 * - `restrict`: Block the delete (the insert wins — data integrity preserved)
 * - `cascade`: Allow the delete and cascade-delete the newly inserted record
 * - `set-null`: Allow the delete and null out the FK on the newly inserted record
 * - `no-action`: Allow the delete (dangling reference is acceptable)
 *
 * @param deleteOp - The delete operation on the referenced record
 * @param insertOp - The concurrent insert operation that references the deleted record
 * @param relation - The relation definition connecting the two collections
 * @returns The resolution action, side effects, and trace
 */
export function resolveDeleteVsInsertConflict(
	deleteOp: Operation,
	insertOp: Operation,
	relation: MergeIncomingRelation,
): DeleteVsInsertResolution {
	const startTime = Date.now()

	switch (relation.onDelete) {
		case 'restrict': {
			// The insert wins — block the delete to preserve referential integrity
			const trace = createDeleteVsInsertTrace(
				deleteOp,
				insertOp,
				relation,
				'referential-restrict',
				'block-delete',
				startTime,
			)
			return {
				action: 'block-delete',
				sideEffects: [],
				trace,
			}
		}

		case 'cascade': {
			// The delete wins — cascade-delete the inserted record
			const sideEffect: SideEffectOp = {
				type: 'delete',
				collection: relation.sourceCollection,
				recordId: insertOp.recordId,
				data: null,
				previousData: null,
				policy: 'cascade',
				relationName: relation.relationName,
			}
			const trace = createDeleteVsInsertTrace(
				deleteOp,
				insertOp,
				relation,
				'referential-cascade',
				'allow-delete',
				startTime,
			)
			return {
				action: 'allow-delete',
				sideEffects: [sideEffect],
				trace,
			}
		}

		case 'set-null': {
			// The delete wins — null out the FK on the inserted record
			const fkValue = insertOp.data !== null ? insertOp.data[relation.foreignKeyField] : undefined
			const sideEffect: SideEffectOp = {
				type: 'update',
				collection: relation.sourceCollection,
				recordId: insertOp.recordId,
				data: { [relation.foreignKeyField]: null },
				previousData: { [relation.foreignKeyField]: fkValue ?? null },
				policy: 'set-null',
				relationName: relation.relationName,
			}
			const trace = createDeleteVsInsertTrace(
				deleteOp,
				insertOp,
				relation,
				'referential-set-null',
				'allow-delete',
				startTime,
			)
			return {
				action: 'allow-delete',
				sideEffects: [sideEffect],
				trace,
			}
		}

		case 'no-action': {
			// Allow the delete — dangling reference is acceptable
			const trace = createDeleteVsInsertTrace(
				deleteOp,
				insertOp,
				relation,
				'referential-no-action',
				'allow-delete',
				startTime,
			)
			return {
				action: 'allow-delete',
				sideEffects: [],
				trace,
			}
		}
	}
}

/**
 * Creates a MergeTrace for a referential integrity decision during delete processing.
 */
function createReferentialTrace(
	deleteOp: Operation,
	relation: MergeIncomingRelation,
	strategy: string,
	referencingRecordIds: string[] | null,
	sideEffects: unknown | null,
	allowed: boolean,
	startTime: number,
): MergeTrace {
	return {
		operationA: deleteOp,
		// For referential integrity checks, operationB is the same as operationA
		// because we are checking constraints against the delete operation itself,
		// not merging two conflicting operations.
		operationB: deleteOp,
		field: `${relation.sourceCollection}.${relation.foreignKeyField}`,
		strategy,
		inputA: { recordId: deleteOp.recordId, collection: deleteOp.collection },
		inputB: referencingRecordIds,
		base: null,
		output: { allowed, sideEffects },
		tier: 2,
		constraintViolated: `referential:${relation.relationName}`,
		duration: Date.now() - startTime,
	}
}

/**
 * Creates a MergeTrace for a delete-vs-insert conflict resolution.
 */
function createDeleteVsInsertTrace(
	deleteOp: Operation,
	insertOp: Operation,
	relation: MergeIncomingRelation,
	strategy: string,
	action: string,
	startTime: number,
): MergeTrace {
	return {
		operationA: deleteOp,
		operationB: insertOp,
		field: `${relation.sourceCollection}.${relation.foreignKeyField}`,
		strategy,
		inputA: { type: 'delete', recordId: deleteOp.recordId, collection: deleteOp.collection },
		inputB: { type: 'insert', recordId: insertOp.recordId, collection: insertOp.collection },
		base: null,
		output: { action },
		tier: 2,
		constraintViolated: `referential:${relation.relationName}`,
		duration: Date.now() - startTime,
	}
}
