import { mkdir, writeFile } from 'node:fs/promises'
import { access } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * Options used to produce a deployable server bundle artifact.
 */
export interface ServerBundleOptions {
	projectRoot: string
	deployDirectory: string
	entryFileCandidates?: readonly string[]
}

/**
 * Result details for the generated server bundle artifact.
 */
export interface ServerBundleResult {
	entryFilePath: string
	outputFilePath: string
}

const DEFAULT_ENTRY_CANDIDATES = [
	'server.ts',
	'server.js',
	'src/server.ts',
	'src/server.js',
] as const
const GENERATED_HEADER = '// Generated by kora deploy — do not edit manually'

/**
 * Generates a placeholder deploy-time server bundle.
 *
 * Phase 13 full bundling will invoke esbuild and produce a single runtime file.
 * This implementation provides deterministic artifact creation and validates that
 * a server entrypoint exists before deployment scaffolding continues.
 */
export async function bundleServer(options: ServerBundleOptions): Promise<ServerBundleResult> {
	const candidates = options.entryFileCandidates ?? DEFAULT_ENTRY_CANDIDATES
	const entryFilePath = await resolveServerEntry(options.projectRoot, candidates)
	if (!entryFilePath) {
		throw new Error(
			`Could not find a server entry file in ${options.projectRoot}. Looked for: ${candidates.join(', ')}`,
		)
	}

	await mkdir(options.deployDirectory, { recursive: true })
	const outputFilePath = join(options.deployDirectory, 'server-bundled.js')
	const source = [
		GENERATED_HEADER,
		'',
		`// Source entry detected at: ${entryFilePath}`,
		'// TODO(phase-13): replace placeholder with esbuild-generated output.',
		'',
		'throw new Error(',
		"  'server-bundled.js is a placeholder artifact. Full bundling is not wired yet.',",
		')',
		'',
	].join('\n')
	await writeFile(outputFilePath, source, 'utf-8')

	return {
		entryFilePath,
		outputFilePath,
	}
}

async function resolveServerEntry(
	projectRoot: string,
	candidates: readonly string[],
): Promise<string | null> {
	for (const candidate of candidates) {
		const fullPath = join(projectRoot, candidate)
		try {
			await access(fullPath)
			return fullPath
		} catch {
			// continue scanning candidates
		}
	}

	return null
}
